# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/HT_search.ui'
#
# Created: Sun Nov 13 14:13:09 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1143, 845)
        self.gridLayout_7 = QtGui.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.HTS_input_file_table = QtGui.QTableWidget(self.groupBox_3)
        self.HTS_input_file_table.setObjectName(_fromUtf8("HTS_input_file_table"))
        self.HTS_input_file_table.setColumnCount(1)
        self.HTS_input_file_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.HTS_input_file_table.setHorizontalHeaderItem(0, item)
        self.HTS_input_file_table.horizontalHeader().setVisible(True)
        self.HTS_input_file_table.horizontalHeader().setCascadingSectionResizes(True)
        self.HTS_input_file_table.horizontalHeader().setDefaultSectionSize(121)
        self.HTS_input_file_table.horizontalHeader().setSortIndicatorShown(True)
        self.HTS_input_file_table.horizontalHeader().setStretchLastSection(True)
        self.HTS_input_file_table.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_3.addWidget(self.HTS_input_file_table)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.HTS_load_input_files_button = QtGui.QPushButton(self.groupBox_3)
        self.HTS_load_input_files_button.setObjectName(_fromUtf8("HTS_load_input_files_button"))
        self.horizontalLayout_9.addWidget(self.HTS_load_input_files_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.HTS_remove_row_button = QtGui.QPushButton(self.groupBox_3)
        self.HTS_remove_row_button.setObjectName(_fromUtf8("HTS_remove_row_button"))
        self.horizontalLayout_9.addWidget(self.HTS_remove_row_button)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(73, 303, 16, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.HTS_define_scan = QtGui.QTableWidget(self.groupBox)
        self.HTS_define_scan.setObjectName(_fromUtf8("HTS_define_scan"))
        self.HTS_define_scan.setColumnCount(1)
        self.HTS_define_scan.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.HTS_define_scan.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_16.addWidget(self.HTS_define_scan)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        spacerItem5 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem5)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.HTS_set_output_file = QtGui.QPushButton(self.groupBox)
        self.HTS_set_output_file.setObjectName(_fromUtf8("HTS_set_output_file"))
        self.horizontalLayout_8.addWidget(self.HTS_set_output_file)
        self.HTS_restore_defaults = QtGui.QPushButton(self.groupBox)
        self.HTS_restore_defaults.setObjectName(_fromUtf8("HTS_restore_defaults"))
        self.horizontalLayout_8.addWidget(self.HTS_restore_defaults)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.HTS_apply_params = QtGui.QPushButton(self.groupBox)
        self.HTS_apply_params.setObjectName(_fromUtf8("HTS_apply_params"))
        self.verticalLayout_10.addWidget(self.HTS_apply_params)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_10.addItem(spacerItem6)
        self.HTS_run_HT_search = QtGui.QPushButton(self.groupBox)
        self.HTS_run_HT_search.setObjectName(_fromUtf8("HTS_run_HT_search"))
        self.verticalLayout_10.addWidget(self.HTS_run_HT_search)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem7 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem7)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_11.addWidget(self.label)
        self.HTS_status_text = QtGui.QPlainTextEdit(self.groupBox)
        self.HTS_status_text.setObjectName(_fromUtf8("HTS_status_text"))
        self.verticalLayout_11.addWidget(self.HTS_status_text)
        self.gridLayout.addLayout(self.verticalLayout_11, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.HT_BS_treatment_field = QtGui.QLineEdit(self.groupBox_4)
        self.HT_BS_treatment_field.setObjectName(_fromUtf8("HT_BS_treatment_field"))
        self.gridLayout_11.addWidget(self.HT_BS_treatment_field, 0, 1, 1, 1)
        self.HT_BS_treatment_browse = QtGui.QPushButton(self.groupBox_4)
        self.HT_BS_treatment_browse.setObjectName(_fromUtf8("HT_BS_treatment_browse"))
        self.gridLayout_11.addWidget(self.HT_BS_treatment_browse, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_11.addWidget(self.label_20, 1, 0, 1, 1)
        self.HT_BS_control_field = QtGui.QLineEdit(self.groupBox_4)
        self.HT_BS_control_field.setObjectName(_fromUtf8("HT_BS_control_field"))
        self.gridLayout_11.addWidget(self.HT_BS_control_field, 1, 1, 1, 1)
        self.HT_BS_control_browse = QtGui.QPushButton(self.groupBox_4)
        self.HT_BS_control_browse.setObjectName(_fromUtf8("HT_BS_control_browse"))
        self.gridLayout_11.addWidget(self.HT_BS_control_browse, 1, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_11.addWidget(self.label_25, 2, 0, 1, 1)
        self.HT_BS_output_field = QtGui.QLineEdit(self.groupBox_4)
        self.HT_BS_output_field.setObjectName(_fromUtf8("HT_BS_output_field"))
        self.gridLayout_11.addWidget(self.HT_BS_output_field, 2, 1, 1, 1)
        self.HT_BS_output_browse = QtGui.QPushButton(self.groupBox_4)
        self.HT_BS_output_browse.setObjectName(_fromUtf8("HT_BS_output_browse"))
        self.gridLayout_11.addWidget(self.HT_BS_output_browse, 2, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 0, 0, 1, 1)
        self.HT_BS_mz_tol = QtGui.QLineEdit(self.groupBox_5)
        self.HT_BS_mz_tol.setObjectName(_fromUtf8("HT_BS_mz_tol"))
        self.gridLayout_12.addWidget(self.HT_BS_mz_tol, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 1, 0, 1, 1)
        self.HT_BS_rt_tol = QtGui.QLineEdit(self.groupBox_5)
        self.HT_BS_rt_tol.setObjectName(_fromUtf8("HT_BS_rt_tol"))
        self.gridLayout_12.addWidget(self.HT_BS_rt_tol, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_12.addWidget(self.label_29, 2, 0, 1, 1)
        self.HT_BS_score_cutoff = QtGui.QLineEdit(self.groupBox_5)
        self.HT_BS_score_cutoff.setObjectName(_fromUtf8("HT_BS_score_cutoff"))
        self.gridLayout_12.addWidget(self.HT_BS_score_cutoff, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout_17.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.HT_BS_active_treatment = QtGui.QRadioButton(self.groupBox_7)
        self.HT_BS_active_treatment.setObjectName(_fromUtf8("HT_BS_active_treatment"))
        self.gridLayout_15.addWidget(self.HT_BS_active_treatment, 0, 0, 1, 1)
        self.HT_BS_active_control = QtGui.QRadioButton(self.groupBox_7)
        self.HT_BS_active_control.setObjectName(_fromUtf8("HT_BS_active_control"))
        self.gridLayout_15.addWidget(self.HT_BS_active_control, 1, 0, 1, 1)
        self.HT_BS_active_output = QtGui.QRadioButton(self.groupBox_7)
        self.HT_BS_active_output.setObjectName(_fromUtf8("HT_BS_active_output"))
        self.gridLayout_15.addWidget(self.HT_BS_active_output, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.HT_BS_run = QtGui.QPushButton(self.groupBox_6)
        self.HT_BS_run.setObjectName(_fromUtf8("HT_BS_run"))
        self.verticalLayout_5.addWidget(self.HT_BS_run)
        spacerItem12 = QtGui.QSpacerItem(20, 118, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.HT_BS_HM = PlotWidget(self.groupBox_6)
        self.HT_BS_HM.setObjectName(_fromUtf8("HT_BS_HM"))
        self.horizontalLayout_13.addWidget(self.HT_BS_HM)
        self.gridLayout_16.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem14 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_9.addWidget(self.label_9, 0, 0, 1, 1)
        self.RP_HT_input_field = QtGui.QLineEdit(self.tab_2)
        self.RP_HT_input_field.setObjectName(_fromUtf8("RP_HT_input_field"))
        self.gridLayout_9.addWidget(self.RP_HT_input_field, 0, 1, 1, 1)
        self.RP_HT_input_button = QtGui.QPushButton(self.tab_2)
        self.RP_HT_input_button.setObjectName(_fromUtf8("RP_HT_input_button"))
        self.gridLayout_9.addWidget(self.RP_HT_input_button, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_9.addWidget(self.label_15, 1, 0, 1, 1)
        self.RP_mascot_input_field = QtGui.QLineEdit(self.tab_2)
        self.RP_mascot_input_field.setObjectName(_fromUtf8("RP_mascot_input_field"))
        self.gridLayout_9.addWidget(self.RP_mascot_input_field, 1, 1, 1, 1)
        self.RP_mascot_input_button = QtGui.QPushButton(self.tab_2)
        self.RP_mascot_input_button.setObjectName(_fromUtf8("RP_mascot_input_button"))
        self.gridLayout_9.addWidget(self.RP_mascot_input_button, 1, 2, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_9)
        spacerItem15 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem16)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem17 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.RP_min_HT_score = QtGui.QLineEdit(self.tab_2)
        self.RP_min_HT_score.setObjectName(_fromUtf8("RP_min_HT_score"))
        self.horizontalLayout_10.addWidget(self.RP_min_HT_score)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        spacerItem18 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.RP_mzWidth = QtGui.QLineEdit(self.tab_2)
        self.RP_mzWidth.setObjectName(_fromUtf8("RP_mzWidth"))
        self.horizontalLayout_6.addWidget(self.RP_mzWidth)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_6)
        spacerItem19 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.RP_rtWidth = QtGui.QLineEdit(self.tab_2)
        self.RP_rtWidth.setObjectName(_fromUtf8("RP_rtWidth"))
        self.horizontalLayout_7.addWidget(self.RP_rtWidth)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_7)
        spacerItem20 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_12.addWidget(self.label_30)
        self.HT_RP_rt_exclusion = QtGui.QLineEdit(self.tab_2)
        self.HT_RP_rt_exclusion.setObjectName(_fromUtf8("HT_RP_rt_exclusion"))
        self.horizontalLayout_12.addWidget(self.HT_RP_rt_exclusion)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem21 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.RP_histogram = PlotWidget(self.tab_2)
        self.RP_histogram.setObjectName(_fromUtf8("RP_histogram"))
        self.verticalLayout.addWidget(self.RP_histogram)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.RP_heat_map = PlotWidget(self.tab_2)
        self.RP_heat_map.setObjectName(_fromUtf8("RP_heat_map"))
        self.verticalLayout_2.addWidget(self.RP_heat_map)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        spacerItem22 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem22)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.HT_RP_use_peptide_isotope_scaling = QtGui.QCheckBox(self.tab_2)
        self.HT_RP_use_peptide_isotope_scaling.setObjectName(_fromUtf8("HT_RP_use_peptide_isotope_scaling"))
        self.horizontalLayout_5.addWidget(self.HT_RP_use_peptide_isotope_scaling)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem24)
        self.HT_RP_plot_EICs = QtGui.QCheckBox(self.tab_2)
        self.HT_RP_plot_EICs.setObjectName(_fromUtf8("HT_RP_plot_EICs"))
        self.horizontalLayout_5.addWidget(self.HT_RP_plot_EICs)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.RP_mzDelta = QtGui.QLineEdit(self.tab_2)
        self.RP_mzDelta.setObjectName(_fromUtf8("RP_mzDelta"))
        self.horizontalLayout.addWidget(self.RP_mzDelta)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_2.addWidget(self.label_18)
        self.RP_EIC_width = QtGui.QLineEdit(self.tab_2)
        self.RP_EIC_width.setObjectName(_fromUtf8("RP_EIC_width"))
        self.horizontalLayout_2.addWidget(self.RP_EIC_width)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem25)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_3.addWidget(self.label_19)
        self.RP_output_file_field = QtGui.QLineEdit(self.tab_2)
        self.RP_output_file_field.setObjectName(_fromUtf8("RP_output_file_field"))
        self.horizontalLayout_3.addWidget(self.RP_output_file_field)
        self.RP_output_file_button = QtGui.QPushButton(self.tab_2)
        self.RP_output_file_button.setObjectName(_fromUtf8("RP_output_file_button"))
        self.horizontalLayout_3.addWidget(self.RP_output_file_button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem26 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem26)
        self.RP_run_button = QtGui.QPushButton(self.tab_2)
        self.RP_run_button.setObjectName(_fromUtf8("RP_run_button"))
        self.verticalLayout_4.addWidget(self.RP_run_button)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.HT_RV_load_results = QtGui.QPushButton(self.tab_6)
        self.HT_RV_load_results.setObjectName(_fromUtf8("HT_RV_load_results"))
        self.horizontalLayout_22.addWidget(self.HT_RV_load_results)
        self.RV_reset = QtGui.QPushButton(self.tab_6)
        self.RV_reset.setObjectName(_fromUtf8("RV_reset"))
        self.horizontalLayout_22.addWidget(self.RV_reset)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.HT_RV_hitlist = QtGui.QTableWidget(self.tab_6)
        self.HT_RV_hitlist.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.HT_RV_hitlist.setObjectName(_fromUtf8("HT_RV_hitlist"))
        self.HT_RV_hitlist.setColumnCount(4)
        self.HT_RV_hitlist.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.HT_RV_hitlist)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.HT_RV_up = QtGui.QPushButton(self.tab_6)
        self.HT_RV_up.setObjectName(_fromUtf8("HT_RV_up"))
        self.horizontalLayout_23.addWidget(self.HT_RV_up)
        self.HT_RV_down = QtGui.QPushButton(self.tab_6)
        self.HT_RV_down.setObjectName(_fromUtf8("HT_RV_down"))
        self.horizontalLayout_23.addWidget(self.HT_RV_down)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.label_28 = QtGui.QLabel(self.tab_6)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_7.addWidget(self.label_28)
        self.HT_RV_accepted_list = QtGui.QTableWidget(self.tab_6)
        self.HT_RV_accepted_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.HT_RV_accepted_list.setAlternatingRowColors(False)
        self.HT_RV_accepted_list.setObjectName(_fromUtf8("HT_RV_accepted_list"))
        self.HT_RV_accepted_list.setColumnCount(4)
        self.HT_RV_accepted_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.HT_RV_accepted_list)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.HT_RV_remove = QtGui.QPushButton(self.tab_6)
        self.HT_RV_remove.setObjectName(_fromUtf8("HT_RV_remove"))
        self.horizontalLayout_24.addWidget(self.HT_RV_remove)
        self.HT_RV_write = QtGui.QPushButton(self.tab_6)
        self.HT_RV_write.setObjectName(_fromUtf8("HT_RV_write"))
        self.horizontalLayout_24.addWidget(self.HT_RV_write)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_21 = QtGui.QLabel(self.tab_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_25.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.tab_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_25.addWidget(self.label_22)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.HT_RV_HM_widget = PlotWidget(self.tab_6)
        self.HT_RV_HM_widget.setObjectName(_fromUtf8("HT_RV_HM_widget"))
        self.horizontalLayout_26.addWidget(self.HT_RV_HM_widget)
        self.HT_RV_EIC = PlotWidget(self.tab_6)
        self.HT_RV_EIC.setObjectName(_fromUtf8("HT_RV_EIC"))
        self.horizontalLayout_26.addWidget(self.HT_RV_EIC)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_27.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.tab_6)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_27.addWidget(self.label_24)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.HT_RV_MS = PlotWidget(self.tab_6)
        self.HT_RV_MS.setObjectName(_fromUtf8("HT_RV_MS"))
        self.verticalLayout_8.addWidget(self.HT_RV_MS)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.HT_RV_accept = QtGui.QPushButton(self.tab_6)
        self.HT_RV_accept.setObjectName(_fromUtf8("HT_RV_accept"))
        self.horizontalLayout_28.addWidget(self.HT_RV_accept)
        self.HT_RV_reject = QtGui.QPushButton(self.tab_6)
        self.HT_RV_reject.setObjectName(_fromUtf8("HT_RV_reject"))
        self.horizontalLayout_28.addWidget(self.HT_RV_reject)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Input mzML files", None))
        item = self.HTS_input_file_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Input File", None))
        self.HTS_load_input_files_button.setText(_translate("Dialog", "Add Input File", None))
        self.HTS_remove_row_button.setText(_translate("Dialog", "Remove Highlighted row", None))
        self.groupBox.setTitle(_translate("Dialog", "Define Search", None))
        item = self.HTS_define_scan.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "mzDelta", None))
        item = self.HTS_define_scan.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Intensity Ratio", None))
        item = self.HTS_define_scan.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "mzWidth", None))
        item = self.HTS_define_scan.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "rtWidth", None))
        item = self.HTS_define_scan.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "mzSigma", None))
        item = self.HTS_define_scan.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "rtSigma", None))
        item = self.HTS_define_scan.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "Threads (CPP only)", None))
        item = self.HTS_define_scan.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "Output File Name", None))
        item = self.HTS_define_scan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Value", None))
        self.HTS_set_output_file.setText(_translate("Dialog", "Set output Directory", None))
        self.HTS_restore_defaults.setText(_translate("Dialog", "Restore Defaults", None))
        self.HTS_apply_params.setText(_translate("Dialog", "Apply Parameters", None))
        self.HTS_run_HT_search.setText(_translate("Dialog", "Run HiTIME search", None))
        self.label.setText(_translate("Dialog", "Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "HiTIME Search", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Input Data", None))
        self.label_13.setText(_translate("Dialog", "Treatment", None))
        self.HT_BS_treatment_browse.setText(_translate("Dialog", "Browse", None))
        self.label_20.setText(_translate("Dialog", "Control", None))
        self.HT_BS_control_browse.setText(_translate("Dialog", "Browse", None))
        self.label_25.setText(_translate("Dialog", "Output", None))
        self.HT_BS_output_browse.setText(_translate("Dialog", "Browse", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Subtraction Parameters", None))
        self.label_26.setText(_translate("Dialog", "m/z Tolerance", None))
        self.label_27.setText(_translate("Dialog", "RT Tolerance", None))
        self.label_29.setText(_translate("Dialog", "Score Cutoff", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Data Viewer", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Active Plot", None))
        self.HT_BS_active_treatment.setText(_translate("Dialog", "Treatment", None))
        self.HT_BS_active_control.setText(_translate("Dialog", "Control", None))
        self.HT_BS_active_output.setText(_translate("Dialog", "Output", None))
        self.HT_BS_run.setText(_translate("Dialog", "Run Subtraction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Background Subtraction", None))
        self.label_9.setText(_translate("Dialog", "HiTIME Output File", None))
        self.RP_HT_input_button.setText(_translate("Dialog", "Browse", None))
        self.label_15.setText(_translate("Dialog", "mzML File", None))
        self.RP_mascot_input_button.setText(_translate("Dialog", "Browse", None))
        self.label_14.setText(_translate("Dialog", "Minimum HT Score", None))
        self.label_12.setText(_translate("Dialog", "m/z Width", None))
        self.label_11.setText(_translate("Dialog", "Retention TIme Width", None))
        self.label_30.setText(_translate("Dialog", "RT exclusion", None))
        self.label_10.setText(_translate("Dialog", "Scores Histogram", None))
        self.label_16.setText(_translate("Dialog", "Heat Map", None))
        self.HT_RP_use_peptide_isotope_scaling.setText(_translate("Dialog", "Use Peptide Isotope Scaling", None))
        self.HT_RP_plot_EICs.setText(_translate("Dialog", "Plot EICs", None))
        self.label_17.setText(_translate("Dialog", "mzDelta", None))
        self.label_18.setText(_translate("Dialog", "EIC Width", None))
        self.label_19.setText(_translate("Dialog", "Output File", None))
        self.RP_output_file_button.setText(_translate("Dialog", "Browse", None))
        self.RP_run_button.setText(_translate("Dialog", "Run Postprocessing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Results Postprocessing", None))
        self.HT_RV_load_results.setText(_translate("Dialog", "Load Results", None))
        self.RV_reset.setText(_translate("Dialog", "Reset", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "RT", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "m/z", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Score", None))
        self.HT_RV_up.setText(_translate("Dialog", "Up", None))
        self.HT_RV_down.setText(_translate("Dialog", "Down", None))
        self.label_28.setText(_translate("Dialog", "Accepted Hits", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "RT", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "m/z", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Score", None))
        self.HT_RV_remove.setText(_translate("Dialog", "Remove", None))
        self.HT_RV_write.setText(_translate("Dialog", "Write Results to File", None))
        self.label_21.setText(_translate("Dialog", "Heat Map", None))
        self.label_22.setText(_translate("Dialog", "EIC", None))
        self.label_23.setText(_translate("Dialog", "MS1 Spectrum", None))
        self.HT_RV_accept.setText(_translate("Dialog", "Accept", None))
        self.HT_RV_reject.setText(_translate("Dialog", "Reject", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Results Viewer", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

