# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/NT_search.ui'
#
# Created: Mon Feb  6 19:55:54 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(979, 889)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.NTPS_RV_accept_2 = QtGui.QTabWidget(Dialog)
        self.NTPS_RV_accept_2.setObjectName(_fromUtf8("NTPS_RV_accept_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_31 = QtGui.QGridLayout(self.tab)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.gridLayout_30 = QtGui.QGridLayout()
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 1, 0, 1, 1)
        self.NTPS_HT_entry = QtGui.QLineEdit(self.groupBox_4)
        self.NTPS_HT_entry.setObjectName(_fromUtf8("NTPS_HT_entry"))
        self.gridLayout_3.addWidget(self.NTPS_HT_entry, 0, 1, 1, 1)
        self.NTPS_mascot_entry_button = QtGui.QPushButton(self.groupBox_4)
        self.NTPS_mascot_entry_button.setObjectName(_fromUtf8("NTPS_mascot_entry_button"))
        self.gridLayout_3.addWidget(self.NTPS_mascot_entry_button, 1, 2, 1, 1)
        self.NTPS_mascot_entry = QtGui.QLineEdit(self.groupBox_4)
        self.NTPS_mascot_entry.setObjectName(_fromUtf8("NTPS_mascot_entry"))
        self.gridLayout_3.addWidget(self.NTPS_mascot_entry, 1, 1, 1, 1)
        self.NTPS_HT_entry_button = QtGui.QPushButton(self.groupBox_4)
        self.NTPS_HT_entry_button.setObjectName(_fromUtf8("NTPS_HT_entry_button"))
        self.gridLayout_3.addWidget(self.NTPS_HT_entry_button, 0, 2, 1, 1)
        self.NTPS_HT_file_charge = QtGui.QLineEdit(self.groupBox_4)
        self.NTPS_HT_file_charge.setMaximumSize(QtCore.QSize(50, 16777215))
        self.NTPS_HT_file_charge.setObjectName(_fromUtf8("NTPS_HT_file_charge"))
        self.gridLayout_3.addWidget(self.NTPS_HT_file_charge, 0, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.NTPS_draw_smiles = QtGui.QPushButton(self.groupBox_8)
        self.NTPS_draw_smiles.setObjectName(_fromUtf8("NTPS_draw_smiles"))
        self.gridLayout_17.addWidget(self.NTPS_draw_smiles, 0, 2, 1, 1)
        self.NTPS_smiles_entry = QtGui.QLineEdit(self.groupBox_8)
        self.NTPS_smiles_entry.setObjectName(_fromUtf8("NTPS_smiles_entry"))
        self.gridLayout_17.addWidget(self.NTPS_smiles_entry, 0, 1, 1, 1)
        self.NTPS_gen_frags = QtGui.QPushButton(self.groupBox_8)
        self.NTPS_gen_frags.setObjectName(_fromUtf8("NTPS_gen_frags"))
        self.gridLayout_17.addWidget(self.NTPS_gen_frags, 1, 0, 1, 3)
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_17.addWidget(self.label_15, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_17)
        self.gridLayout_32 = QtGui.QGridLayout()
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.NTPS_mod_comp_table = QtGui.QTableWidget(self.groupBox_8)
        self.NTPS_mod_comp_table.setObjectName(_fromUtf8("NTPS_mod_comp_table"))
        self.NTPS_mod_comp_table.setColumnCount(2)
        self.NTPS_mod_comp_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.NTPS_mod_comp_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.NTPS_mod_comp_table.setHorizontalHeaderItem(1, item)
        self.gridLayout_32.addWidget(self.NTPS_mod_comp_table, 0, 0, 1, 1)
        self.NTPS_add_element_row = QtGui.QPushButton(self.groupBox_8)
        self.NTPS_add_element_row.setObjectName(_fromUtf8("NTPS_add_element_row"))
        self.gridLayout_32.addWidget(self.NTPS_add_element_row, 1, 0, 1, 1)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.NTPS_frag_list_up_button = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NTPS_frag_list_up_button.sizePolicy().hasHeightForWidth())
        self.NTPS_frag_list_up_button.setSizePolicy(sizePolicy)
        self.NTPS_frag_list_up_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.NTPS_frag_list_up_button.setObjectName(_fromUtf8("NTPS_frag_list_up_button"))
        self.gridLayout_14.addWidget(self.NTPS_frag_list_up_button, 0, 0, 1, 1)
        self.NTPS_frag_list_down_button = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NTPS_frag_list_down_button.sizePolicy().hasHeightForWidth())
        self.NTPS_frag_list_down_button.setSizePolicy(sizePolicy)
        self.NTPS_frag_list_down_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.NTPS_frag_list_down_button.setObjectName(_fromUtf8("NTPS_frag_list_down_button"))
        self.gridLayout_14.addWidget(self.NTPS_frag_list_down_button, 0, 1, 1, 1)
        self.NTPS_frag_list = QtGui.QListWidget(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NTPS_frag_list.sizePolicy().hasHeightForWidth())
        self.NTPS_frag_list.setSizePolicy(sizePolicy)
        self.NTPS_frag_list.setMinimumSize(QtCore.QSize(100, 0))
        self.NTPS_frag_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.NTPS_frag_list.setObjectName(_fromUtf8("NTPS_frag_list"))
        self.gridLayout_14.addWidget(self.NTPS_frag_list, 1, 0, 1, 2)
        self.gridLayout_14.setRowStretch(1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_14, 0, 1, 2, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_32)
        self.gridLayout_18.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_8)
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.NTPS_structure_view = QtGui.QGraphicsView(self.groupBox_13)
        self.NTPS_structure_view.setObjectName(_fromUtf8("NTPS_structure_view"))
        self.gridLayout_11.addWidget(self.NTPS_structure_view, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_13)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_30.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_21 = QtGui.QGroupBox(self.tab)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_21)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_48 = QtGui.QLabel(self.groupBox_5)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_5.addWidget(self.label_48, 0, 0, 1, 1)
        self.NTPS_mascot_threshold_identity = QtGui.QRadioButton(self.groupBox_5)
        self.NTPS_mascot_threshold_identity.setChecked(True)
        self.NTPS_mascot_threshold_identity.setObjectName(_fromUtf8("NTPS_mascot_threshold_identity"))
        self.gridLayout_5.addWidget(self.NTPS_mascot_threshold_identity, 0, 1, 1, 1)
        self.NTPS_mascot_threshold_homology = QtGui.QRadioButton(self.groupBox_5)
        self.NTPS_mascot_threshold_homology.setObjectName(_fromUtf8("NTPS_mascot_threshold_homology"))
        self.gridLayout_5.addWidget(self.NTPS_mascot_threshold_homology, 1, 1, 1, 1)
        self.NTPS_toMinutes = QtGui.QCheckBox(self.groupBox_5)
        self.NTPS_toMinutes.setChecked(True)
        self.NTPS_toMinutes.setObjectName(_fromUtf8("NTPS_toMinutes"))
        self.gridLayout_5.addWidget(self.NTPS_toMinutes, 0, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_43 = QtGui.QLabel(self.groupBox_5)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_6.addWidget(self.label_43, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_50 = QtGui.QLabel(self.groupBox_5)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_4.addWidget(self.label_50)
        self.NTPS_min_HT_score_2 = QtGui.QLineEdit(self.groupBox_5)
        self.NTPS_min_HT_score_2.setObjectName(_fromUtf8("NTPS_min_HT_score_2"))
        self.horizontalLayout_4.addWidget(self.NTPS_min_HT_score_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_49 = QtGui.QLabel(self.groupBox_5)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_10.addWidget(self.label_49)
        self.NTPS_min_HT_score_3 = QtGui.QLineEdit(self.groupBox_5)
        self.NTPS_min_HT_score_3.setObjectName(_fromUtf8("NTPS_min_HT_score_3"))
        self.horizontalLayout_10.addWidget(self.NTPS_min_HT_score_3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_10)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
        self.NTPS_min_HT_score = QtGui.QLineEdit(self.groupBox_6)
        self.NTPS_min_HT_score.setObjectName(_fromUtf8("NTPS_min_HT_score"))
        self.gridLayout_7.addWidget(self.NTPS_min_HT_score, 0, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_6)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_7.addWidget(self.label_46, 1, 0, 1, 1)
        self.NTPS_HT_MS2_mz_offset = QtGui.QLineEdit(self.groupBox_6)
        self.NTPS_HT_MS2_mz_offset.setObjectName(_fromUtf8("NTPS_HT_MS2_mz_offset"))
        self.gridLayout_7.addWidget(self.NTPS_HT_MS2_mz_offset, 1, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_6)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_7.addWidget(self.label_47, 2, 0, 1, 1)
        self.NTPS_HT_MS2_rt_offset = QtGui.QLineEdit(self.groupBox_6)
        self.NTPS_HT_MS2_rt_offset.setObjectName(_fromUtf8("NTPS_HT_MS2_rt_offset"))
        self.gridLayout_7.addWidget(self.NTPS_HT_MS2_rt_offset, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.gridLayout_20.addLayout(self.verticalLayout_2, 0, 0, 3, 1)
        self.groupBox_18 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_18)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_19 = QtGui.QGroupBox(self.groupBox_18)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_19)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.NTPS_ion_types_a = QtGui.QCheckBox(self.groupBox_19)
        self.NTPS_ion_types_a.setObjectName(_fromUtf8("NTPS_ion_types_a"))
        self.gridLayout_9.addWidget(self.NTPS_ion_types_a, 0, 0, 1, 1)
        self.NTPS_ion_types_b = QtGui.QCheckBox(self.groupBox_19)
        self.NTPS_ion_types_b.setObjectName(_fromUtf8("NTPS_ion_types_b"))
        self.gridLayout_9.addWidget(self.NTPS_ion_types_b, 0, 1, 1, 1)
        self.NTPS_ion_types_c = QtGui.QCheckBox(self.groupBox_19)
        self.NTPS_ion_types_c.setObjectName(_fromUtf8("NTPS_ion_types_c"))
        self.gridLayout_9.addWidget(self.NTPS_ion_types_c, 0, 2, 1, 1)
        self.NTPS_ion_types_x = QtGui.QCheckBox(self.groupBox_19)
        self.NTPS_ion_types_x.setObjectName(_fromUtf8("NTPS_ion_types_x"))
        self.gridLayout_9.addWidget(self.NTPS_ion_types_x, 1, 0, 1, 1)
        self.NTPS_ion_types_y = QtGui.QCheckBox(self.groupBox_19)
        self.NTPS_ion_types_y.setObjectName(_fromUtf8("NTPS_ion_types_y"))
        self.gridLayout_9.addWidget(self.NTPS_ion_types_y, 1, 1, 1, 1)
        self.NTPS_ion_types_z = QtGui.QCheckBox(self.groupBox_19)
        self.NTPS_ion_types_z.setObjectName(_fromUtf8("NTPS_ion_types_z"))
        self.gridLayout_9.addWidget(self.NTPS_ion_types_z, 1, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_19)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_28 = QtGui.QLabel(self.groupBox_18)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_11.addWidget(self.label_28)
        self.NTPS_ms2_match_tol = QtGui.QLineEdit(self.groupBox_18)
        self.NTPS_ms2_match_tol.setObjectName(_fromUtf8("NTPS_ms2_match_tol"))
        self.horizontalLayout_11.addWidget(self.NTPS_ms2_match_tol)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.groupBox_20 = QtGui.QGroupBox(self.groupBox_18)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_20)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.NTPS_reactive_residues_C = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_C.setObjectName(_fromUtf8("NTPS_reactive_residues_C"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_C, 0, 0, 1, 1)
        self.NTPS_reactive_residues_Y = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_Y.setObjectName(_fromUtf8("NTPS_reactive_residues_Y"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_Y, 0, 1, 1, 1)
        self.NTPS_reactive_residues_W = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_W.setObjectName(_fromUtf8("NTPS_reactive_residues_W"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_W, 0, 2, 1, 1)
        self.NTPS_reactive_residues_H = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_H.setObjectName(_fromUtf8("NTPS_reactive_residues_H"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_H, 0, 3, 1, 1)
        self.NTPS_reactive_residues_M = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_M.setObjectName(_fromUtf8("NTPS_reactive_residues_M"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_M, 1, 0, 1, 1)
        self.NTPS_reactive_residues_K = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_K.setObjectName(_fromUtf8("NTPS_reactive_residues_K"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_K, 1, 1, 1, 1)
        self.NTPS_reactive_residues_R = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_R.setObjectName(_fromUtf8("NTPS_reactive_residues_R"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_R, 1, 2, 1, 1)
        self.NTPS_reactive_residues_Q = QtGui.QCheckBox(self.groupBox_20)
        self.NTPS_reactive_residues_Q.setObjectName(_fromUtf8("NTPS_reactive_residues_Q"))
        self.gridLayout_25.addWidget(self.NTPS_reactive_residues_Q, 1, 3, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_20)
        self.gridLayout_16.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_18, 0, 1, 3, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.label_44 = QtGui.QLabel(self.groupBox_7)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_27.addWidget(self.label_44, 0, 0, 1, 1)
        self.NTPS_mz_band_entry = QtGui.QLineEdit(self.groupBox_7)
        self.NTPS_mz_band_entry.setObjectName(_fromUtf8("NTPS_mz_band_entry"))
        self.gridLayout_27.addWidget(self.NTPS_mz_band_entry, 0, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_7)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_27.addWidget(self.label_45, 1, 0, 1, 1)
        self.NTPS_max_RME = QtGui.QLineEdit(self.groupBox_7)
        self.NTPS_max_RME.setObjectName(_fromUtf8("NTPS_max_RME"))
        self.gridLayout_27.addWidget(self.NTPS_max_RME, 1, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_7)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_27.addWidget(self.label_40, 2, 0, 1, 1)
        self.NTPS_ppm_tol = QtGui.QLineEdit(self.groupBox_7)
        self.NTPS_ppm_tol.setObjectName(_fromUtf8("NTPS_ppm_tol"))
        self.gridLayout_27.addWidget(self.NTPS_ppm_tol, 2, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_7, 0, 2, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.gridLayout_29 = QtGui.QGridLayout()
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_29.addWidget(self.checkBox, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.NTPS_output_file_field = QtGui.QLineEdit(self.groupBox_9)
        self.NTPS_output_file_field.setObjectName(_fromUtf8("NTPS_output_file_field"))
        self.horizontalLayout_12.addWidget(self.NTPS_output_file_field)
        self.NTPS_output_browse = QtGui.QPushButton(self.groupBox_9)
        self.NTPS_output_browse.setObjectName(_fromUtf8("NTPS_output_browse"))
        self.horizontalLayout_12.addWidget(self.NTPS_output_browse)
        self.gridLayout_29.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_9, 1, 2, 1, 1)
        self.NTPS_plot_tool = QtGui.QPushButton(self.groupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NTPS_plot_tool.sizePolicy().hasHeightForWidth())
        self.NTPS_plot_tool.setSizePolicy(sizePolicy)
        self.NTPS_plot_tool.setObjectName(_fromUtf8("NTPS_plot_tool"))
        self.gridLayout_20.addWidget(self.NTPS_plot_tool, 2, 2, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_21, 2, 0, 1, 1)
        self.NTPS_run = QtGui.QPushButton(self.tab)
        self.NTPS_run.setObjectName(_fromUtf8("NTPS_run"))
        self.gridLayout_30.addWidget(self.NTPS_run, 3, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.NTPS_RV_accept_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.NTPS_RV_hits = QtGui.QTableWidget(self.groupBox_2)
        self.NTPS_RV_hits.setObjectName(_fromUtf8("NTPS_RV_hits"))
        self.NTPS_RV_hits.setColumnCount(2)
        self.NTPS_RV_hits.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_hits.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_hits.setHorizontalHeaderItem(1, item)
        self.gridLayout_21.addWidget(self.NTPS_RV_hits, 1, 0, 1, 2)
        self.NTPS_RV_up = QtGui.QPushButton(self.groupBox_2)
        self.NTPS_RV_up.setObjectName(_fromUtf8("NTPS_RV_up"))
        self.gridLayout_21.addWidget(self.NTPS_RV_up, 2, 0, 1, 1)
        self.NTPS_RV_down = QtGui.QPushButton(self.groupBox_2)
        self.NTPS_RV_down.setObjectName(_fromUtf8("NTPS_RV_down"))
        self.gridLayout_21.addWidget(self.NTPS_RV_down, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_21.addWidget(self.label_5, 3, 0, 1, 1)
        self.NTPS_RV_accepted_hits = QtGui.QTableWidget(self.groupBox_2)
        self.NTPS_RV_accepted_hits.setObjectName(_fromUtf8("NTPS_RV_accepted_hits"))
        self.NTPS_RV_accepted_hits.setColumnCount(2)
        self.NTPS_RV_accepted_hits.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_accepted_hits.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_accepted_hits.setHorizontalHeaderItem(1, item)
        self.gridLayout_21.addWidget(self.NTPS_RV_accepted_hits, 4, 0, 1, 2)
        self.NTPS_RV_remove = QtGui.QPushButton(self.groupBox_2)
        self.NTPS_RV_remove.setObjectName(_fromUtf8("NTPS_RV_remove"))
        self.gridLayout_21.addWidget(self.NTPS_RV_remove, 5, 0, 1, 1)
        self.NTPS_RV_write_report = QtGui.QPushButton(self.groupBox_2)
        self.NTPS_RV_write_report.setObjectName(_fromUtf8("NTPS_RV_write_report"))
        self.gridLayout_21.addWidget(self.NTPS_RV_write_report, 5, 1, 1, 1)
        self.NTPS_RV_load_results = QtGui.QPushButton(self.groupBox_2)
        self.NTPS_RV_load_results.setObjectName(_fromUtf8("NTPS_RV_load_results"))
        self.gridLayout_21.addWidget(self.NTPS_RV_load_results, 0, 0, 1, 1)
        self.NTPS_RV_reset = QtGui.QPushButton(self.groupBox_2)
        self.NTPS_RV_reset.setObjectName(_fromUtf8("NTPS_RV_reset"))
        self.gridLayout_21.addWidget(self.NTPS_RV_reset, 0, 1, 1, 1)
        self.gridLayout_21.setRowStretch(0, 2)
        self.gridLayout_22.addLayout(self.gridLayout_21, 2, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.NTPS_RV_mascot_score = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_mascot_score.setText(_fromUtf8(""))
        self.NTPS_RV_mascot_score.setObjectName(_fromUtf8("NTPS_RV_mascot_score"))
        self.gridLayout.addWidget(self.NTPS_RV_mascot_score, 3, 1, 1, 1)
        self.NTPS_RV_mod_mass = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_mod_mass.setText(_fromUtf8(""))
        self.NTPS_RV_mod_mass.setObjectName(_fromUtf8("NTPS_RV_mod_mass"))
        self.gridLayout.addWidget(self.NTPS_RV_mod_mass, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.NT_RV_delta_RT = QtGui.QLabel(self.groupBox_3)
        self.NT_RV_delta_RT.setText(_fromUtf8(""))
        self.NT_RV_delta_RT.setObjectName(_fromUtf8("NT_RV_delta_RT"))
        self.gridLayout.addWidget(self.NT_RV_delta_RT, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.NTPS_RV_sequence = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_sequence.setText(_fromUtf8(""))
        self.NTPS_RV_sequence.setObjectName(_fromUtf8("NTPS_RV_sequence"))
        self.gridLayout.addWidget(self.NTPS_RV_sequence, 6, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.NTPS_RV_mod_site = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_mod_site.setText(_fromUtf8(""))
        self.NTPS_RV_mod_site.setObjectName(_fromUtf8("NTPS_RV_mod_site"))
        self.gridLayout.addWidget(self.NTPS_RV_mod_site, 7, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.NTPS_RV_correlation_score = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_correlation_score.setText(_fromUtf8(""))
        self.NTPS_RV_correlation_score.setObjectName(_fromUtf8("NTPS_RV_correlation_score"))
        self.gridLayout.addWidget(self.NTPS_RV_correlation_score, 5, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.NTPS_RV_HT_score = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_HT_score.setText(_fromUtf8(""))
        self.NTPS_RV_HT_score.setObjectName(_fromUtf8("NTPS_RV_HT_score"))
        self.gridLayout.addWidget(self.NTPS_RV_HT_score, 2, 1, 1, 1)
        self.NTPS_RV_mascot_identity_homology = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_mascot_identity_homology.setText(_fromUtf8(""))
        self.NTPS_RV_mascot_identity_homology.setObjectName(_fromUtf8("NTPS_RV_mascot_identity_homology"))
        self.gridLayout.addWidget(self.NTPS_RV_mascot_identity_homology, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        self.NTPS_RV_HT_MZ = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_HT_MZ.setText(_fromUtf8(""))
        self.NTPS_RV_HT_MZ.setObjectName(_fromUtf8("NTPS_RV_HT_MZ"))
        self.gridLayout.addWidget(self.NTPS_RV_HT_MZ, 8, 1, 1, 1)
        self.NTPS_RV_HT_RT = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_HT_RT.setText(_fromUtf8(""))
        self.NTPS_RV_HT_RT.setObjectName(_fromUtf8("NTPS_RV_HT_RT"))
        self.gridLayout.addWidget(self.NTPS_RV_HT_RT, 9, 1, 1, 1)
        self.NTPS_RV_Mascot_MZ = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_Mascot_MZ.setText(_fromUtf8(""))
        self.NTPS_RV_Mascot_MZ.setObjectName(_fromUtf8("NTPS_RV_Mascot_MZ"))
        self.gridLayout.addWidget(self.NTPS_RV_Mascot_MZ, 10, 1, 1, 1)
        self.NTPS_RV_Mascot_RT = QtGui.QLabel(self.groupBox_3)
        self.NTPS_RV_Mascot_RT.setText(_fromUtf8(""))
        self.NTPS_RV_Mascot_RT.setObjectName(_fromUtf8("NTPS_RV_Mascot_RT"))
        self.gridLayout.addWidget(self.NTPS_RV_Mascot_RT, 11, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.NTPS_RV_formulae = QtGui.QTableWidget(self.groupBox_3)
        self.NTPS_RV_formulae.setObjectName(_fromUtf8("NTPS_RV_formulae"))
        self.NTPS_RV_formulae.setColumnCount(3)
        self.NTPS_RV_formulae.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_formulae.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_formulae.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.NTPS_RV_formulae.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.NTPS_RV_formulae)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.NTPS_RV_HM = PlotWidget(self.groupBox_3)
        self.NTPS_RV_HM.setObjectName(_fromUtf8("NTPS_RV_HM"))
        self.verticalLayout_7.addWidget(self.NTPS_RV_HM)
        self.NTPS_RV_structure = QtGui.QGraphicsView(self.groupBox_3)
        self.NTPS_RV_structure.setObjectName(_fromUtf8("NTPS_RV_structure"))
        self.verticalLayout_7.addWidget(self.NTPS_RV_structure)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.NTPS_RV_MS = PlotWidget(self.groupBox_3)
        self.NTPS_RV_MS.setObjectName(_fromUtf8("NTPS_RV_MS"))
        self.gridLayout_24.addWidget(self.NTPS_RV_MS, 0, 0, 1, 2)
        self.NTPS_RV_accept = QtGui.QPushButton(self.groupBox_3)
        self.NTPS_RV_accept.setObjectName(_fromUtf8("NTPS_RV_accept"))
        self.gridLayout_24.addWidget(self.NTPS_RV_accept, 1, 0, 1, 1)
        self.NTPS_RV_reject = QtGui.QPushButton(self.groupBox_3)
        self.NTPS_RV_reject.setObjectName(_fromUtf8("NTPS_RV_reject"))
        self.gridLayout_24.addWidget(self.NTPS_RV_reject, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_24)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.gridLayout_23.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.NTPS_RV_accept_2.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.NTPS_RV_accept_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.NTPS_RV_accept_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Data Input", None))
        self.label_30.setText(_translate("Dialog", "HiTIME", None))
        self.label_32.setText(_translate("Dialog", "Mascot", None))
        self.NTPS_mascot_entry_button.setText(_translate("Dialog", "Browse", None))
        self.NTPS_HT_entry_button.setText(_translate("Dialog", "Browse", None))
        self.label_14.setText(_translate("Dialog", "HT charge", None))
        self.groupBox.setTitle(_translate("Dialog", "Search Parameters", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Define Input Molecule", None))
        self.NTPS_draw_smiles.setText(_translate("Dialog", "Draw Structure", None))
        self.NTPS_gen_frags.setText(_translate("Dialog", "Generate Fragments From Structure", None))
        self.label_15.setText(_translate("Dialog", "Smiles String", None))
        item = self.NTPS_mod_comp_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Element", None))
        item = self.NTPS_mod_comp_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Ranges", None))
        self.NTPS_add_element_row.setText(_translate("Dialog", "Add Element Row", None))
        self.NTPS_frag_list_up_button.setText(_translate("Dialog", "Up", None))
        self.NTPS_frag_list_down_button.setText(_translate("Dialog", "Down", None))
        self.groupBox_13.setTitle(_translate("Dialog", "Structure Viewer", None))
        self.groupBox_21.setTitle(_translate("Dialog", "Filter Options", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Peptide Selection Parameters", None))
        self.label_48.setText(_translate("Dialog", "Mascot Threshold", None))
        self.NTPS_mascot_threshold_identity.setText(_translate("Dialog", "Identity", None))
        self.NTPS_mascot_threshold_homology.setText(_translate("Dialog", "Homology", None))
        self.NTPS_toMinutes.setText(_translate("Dialog", "Convert to mins", None))
        self.label_43.setText(_translate("Dialog", "Charge State Range", None))
        self.label_50.setText(_translate("Dialog", "Min", None))
        self.label_49.setText(_translate("Dialog", "Max", None))
        self.groupBox_6.setTitle(_translate("Dialog", "HiTIME Selection Parameters", None))
        self.label_31.setText(_translate("Dialog", "Min HT Score", None))
        self.label_46.setText(_translate("Dialog", "HT MS2 mz offset", None))
        self.label_47.setText(_translate("Dialog", "HT MS2 RT offset", None))
        self.groupBox_18.setTitle(_translate("Dialog", "MS/MS correlation parameters", None))
        self.groupBox_19.setTitle(_translate("Dialog", "Match Ion Types", None))
        self.NTPS_ion_types_a.setText(_translate("Dialog", "a", None))
        self.NTPS_ion_types_b.setText(_translate("Dialog", "b", None))
        self.NTPS_ion_types_c.setText(_translate("Dialog", "c", None))
        self.NTPS_ion_types_x.setText(_translate("Dialog", "x", None))
        self.NTPS_ion_types_y.setText(_translate("Dialog", "y", None))
        self.NTPS_ion_types_z.setText(_translate("Dialog", "z", None))
        self.label_28.setText(_translate("Dialog", "Match Tolerance (m/z)", None))
        self.groupBox_20.setTitle(_translate("Dialog", "Reactive Residues", None))
        self.NTPS_reactive_residues_C.setText(_translate("Dialog", "C", None))
        self.NTPS_reactive_residues_Y.setText(_translate("Dialog", "Y", None))
        self.NTPS_reactive_residues_W.setText(_translate("Dialog", "W", None))
        self.NTPS_reactive_residues_H.setText(_translate("Dialog", "H", None))
        self.NTPS_reactive_residues_M.setText(_translate("Dialog", "M", None))
        self.NTPS_reactive_residues_K.setText(_translate("Dialog", "K", None))
        self.NTPS_reactive_residues_R.setText(_translate("Dialog", "R", None))
        self.NTPS_reactive_residues_Q.setText(_translate("Dialog", "Q", None))
        self.groupBox_7.setTitle(_translate("Dialog", "CRM Parameters", None))
        self.label_44.setText(_translate("Dialog", "m/z band", None))
        self.label_45.setText(_translate("Dialog", "Max. RME", None))
        self.label_40.setText(_translate("Dialog", "ppm tolerance", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Output", None))
        self.checkBox.setText(_translate("Dialog", "Write Log File", None))
        self.NTPS_output_browse.setText(_translate("Dialog", "Browse", None))
        self.NTPS_plot_tool.setText(_translate("Dialog", "Plotting Tool", None))
        self.NTPS_run.setText(_translate("Dialog", "Run Analysis", None))
        self.NTPS_RV_accept_2.setTabText(self.NTPS_RV_accept_2.indexOf(self.tab), _translate("Dialog", "Non-targeted PTM search", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Results Summary", None))
        item = self.NTPS_RV_hits.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.NTPS_RV_hits.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "m/z", None))
        self.NTPS_RV_up.setText(_translate("Dialog", "Up", None))
        self.NTPS_RV_down.setText(_translate("Dialog", "Down", None))
        self.label_5.setText(_translate("Dialog", "Accepted Hits", None))
        item = self.NTPS_RV_accepted_hits.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.NTPS_RV_accepted_hits.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Formula", None))
        self.NTPS_RV_remove.setText(_translate("Dialog", "Remove", None))
        self.NTPS_RV_write_report.setText(_translate("Dialog", "Write Report", None))
        self.NTPS_RV_load_results.setText(_translate("Dialog", "Load Results", None))
        self.NTPS_RV_reset.setText(_translate("Dialog", "Reset", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Details", None))
        self.label_9.setText(_translate("Dialog", "Sequence", None))
        self.label_7.setText(_translate("Dialog", "Mascot Score", None))
        self.label_2.setText(_translate("Dialog", "Delta m/z", None))
        self.label_3.setText(_translate("Dialog", "Delta RT", None))
        self.label_11.setText(_translate("Dialog", "Modification Site", None))
        self.label_4.setText(_translate("Dialog", "Correlation Score", None))
        self.label.setText(_translate("Dialog", "HiTIME Score", None))
        self.label_6.setText(_translate("Dialog", "Identity/Homology", None))
        self.label_8.setText(_translate("Dialog", "HT m/z", None))
        self.label_10.setText(_translate("Dialog", "HT RT", None))
        self.label_12.setText(_translate("Dialog", "Mascot m/z", None))
        self.label_13.setText(_translate("Dialog", "Mascot RT", None))
        item = self.NTPS_RV_formulae.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Formula", None))
        item = self.NTPS_RV_formulae.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ppm", None))
        item = self.NTPS_RV_formulae.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Residual Mass", None))
        self.NTPS_RV_accept.setText(_translate("Dialog", "Accept", None))
        self.NTPS_RV_reject.setText(_translate("Dialog", "Reject", None))
        self.NTPS_RV_accept_2.setTabText(self.NTPS_RV_accept_2.indexOf(self.tab_2), _translate("Dialog", "Results Viewer", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

