# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/T_search.ui'
#
# Created: Wed Nov  9 15:02:05 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1149, 960)
        self.gridLayout_13 = QtGui.QGridLayout(Dialog)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.T_mascot_file = QtGui.QLineEdit(self.groupBox)
        self.T_mascot_file.setObjectName(_fromUtf8("T_mascot_file"))
        self.gridLayout.addWidget(self.T_mascot_file, 0, 1, 1, 1)
        self.T_browse_mascot = QtGui.QPushButton(self.groupBox)
        self.T_browse_mascot.setObjectName(_fromUtf8("T_browse_mascot"))
        self.gridLayout.addWidget(self.T_browse_mascot, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.T_HT_files = QtGui.QTableWidget(self.groupBox)
        self.T_HT_files.setObjectName(_fromUtf8("T_HT_files"))
        self.T_HT_files.setColumnCount(2)
        self.T_HT_files.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.T_HT_files.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.T_HT_files.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.T_HT_files, 0, 1, 3, 1)
        self.T_HT_add = QtGui.QPushButton(self.groupBox)
        self.T_HT_add.setObjectName(_fromUtf8("T_HT_add"))
        self.gridLayout_4.addWidget(self.T_HT_add, 0, 2, 1, 1)
        self.T_HT_remove = QtGui.QPushButton(self.groupBox)
        self.T_HT_remove.setObjectName(_fromUtf8("T_HT_remove"))
        self.gridLayout_4.addWidget(self.T_HT_remove, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout_10.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_10.addItem(spacerItem3, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.T_CRM_mods = QtGui.QTableWidget(self.groupBox_2)
        self.T_CRM_mods.setObjectName(_fromUtf8("T_CRM_mods"))
        self.T_CRM_mods.setColumnCount(2)
        self.T_CRM_mods.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.T_CRM_mods.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.T_CRM_mods.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.T_CRM_mods, 0, 3, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.T_mods_add = QtGui.QPushButton(self.groupBox_2)
        self.T_mods_add.setObjectName(_fromUtf8("T_mods_add"))
        self.verticalLayout_4.addWidget(self.T_mods_add)
        self.T_mods_remove = QtGui.QPushButton(self.groupBox_2)
        self.T_mods_remove.setObjectName(_fromUtf8("T_mods_remove"))
        self.verticalLayout_4.addWidget(self.T_mods_remove)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 0, 0, 1, 1)
        self.T_all_mods = QtGui.QTableWidget(self.groupBox_2)
        self.T_all_mods.setObjectName(_fromUtf8("T_all_mods"))
        self.T_all_mods.setColumnCount(2)
        self.T_all_mods.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.T_all_mods.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.T_all_mods.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.T_all_mods, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 1, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_2, 2, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_10.addItem(spacerItem6, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.HT_score_cutoff = QtGui.QLineEdit(self.groupBox_3)
        self.HT_score_cutoff.setObjectName(_fromUtf8("HT_score_cutoff"))
        self.horizontalLayout_3.addWidget(self.HT_score_cutoff)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.T_remove_duplicates = QtGui.QCheckBox(self.groupBox_3)
        self.T_remove_duplicates.setObjectName(_fromUtf8("T_remove_duplicates"))
        self.horizontalLayout_7.addWidget(self.T_remove_duplicates)
        self.T_get_indirect = QtGui.QCheckBox(self.groupBox_3)
        self.T_get_indirect.setObjectName(_fromUtf8("T_get_indirect"))
        self.horizontalLayout_7.addWidget(self.T_get_indirect)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 3, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 4, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.T_HT_rtGap = QtGui.QLineEdit(self.groupBox_3)
        self.T_HT_rtGap.setObjectName(_fromUtf8("T_HT_rtGap"))
        self.horizontalLayout_5.addWidget(self.T_HT_rtGap)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.T_plot_EICs = QtGui.QCheckBox(self.groupBox_3)
        self.T_plot_EICs.setObjectName(_fromUtf8("T_plot_EICs"))
        self.gridLayout_2.addWidget(self.T_plot_EICs, 1, 3, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.T_HT_mzGap = QtGui.QLineEdit(self.groupBox_3)
        self.T_HT_mzGap.setObjectName(_fromUtf8("T_HT_mzGap"))
        self.horizontalLayout_6.addWidget(self.T_HT_mzGap)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.T_mzM_file = QtGui.QLineEdit(self.groupBox_3)
        self.T_mzM_file.setObjectName(_fromUtf8("T_mzM_file"))
        self.horizontalLayout_2.addWidget(self.T_mzM_file)
        self.T_browse_mzML = QtGui.QPushButton(self.groupBox_3)
        self.T_browse_mzML.setObjectName(_fromUtf8("T_browse_mzML"))
        self.horizontalLayout_2.addWidget(self.T_browse_mzML)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 3, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.T_NMD = QtGui.QLineEdit(self.groupBox_3)
        self.T_NMD.setObjectName(_fromUtf8("T_NMD"))
        self.horizontalLayout_4.addWidget(self.T_NMD)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.T_mzML_file2 = QtGui.QLineEdit(self.groupBox_3)
        self.T_mzML_file2.setObjectName(_fromUtf8("T_mzML_file2"))
        self.horizontalLayout_10.addWidget(self.T_mzML_file2)
        self.T_browse_mzML2 = QtGui.QPushButton(self.groupBox_3)
        self.T_browse_mzML2.setObjectName(_fromUtf8("T_browse_mzML2"))
        self.horizontalLayout_10.addWidget(self.T_browse_mzML2)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 3, 3, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.T_HT_peptide_correlation_RT = QtGui.QLineEdit(self.groupBox_3)
        self.T_HT_peptide_correlation_RT.setObjectName(_fromUtf8("T_HT_peptide_correlation_RT"))
        self.horizontalLayout_12.addWidget(self.T_HT_peptide_correlation_RT)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 4, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_16.addWidget(self.label_13)
        self.T_eicWidth = QtGui.QLineEdit(self.groupBox_3)
        self.T_eicWidth.setObjectName(_fromUtf8("T_eicWidth"))
        self.horizontalLayout_16.addWidget(self.T_eicWidth)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 4, 3, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.T_HT_peptide_correlation_mz = QtGui.QLineEdit(self.groupBox_3)
        self.T_HT_peptide_correlation_mz.setObjectName(_fromUtf8("T_HT_peptide_correlation_mz"))
        self.horizontalLayout_18.addWidget(self.T_HT_peptide_correlation_mz)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 5, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.T_outputFile_text = QtGui.QLineEdit(self.groupBox_3)
        self.T_outputFile_text.setObjectName(_fromUtf8("T_outputFile_text"))
        self.horizontalLayout.addWidget(self.T_outputFile_text)
        self.T_outputFile_button = QtGui.QPushButton(self.groupBox_3)
        self.T_outputFile_button.setObjectName(_fromUtf8("T_outputFile_button"))
        self.horizontalLayout.addWidget(self.T_outputFile_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.T_run = QtGui.QPushButton(self.tab_3)
        self.T_run.setObjectName(_fromUtf8("T_run"))
        self.gridLayout_10.addWidget(self.T_run, 5, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.RV_load_results = QtGui.QPushButton(self.tab_6)
        self.RV_load_results.setObjectName(_fromUtf8("RV_load_results"))
        self.horizontalLayout_15.addWidget(self.RV_load_results)
        self.RV_reset = QtGui.QPushButton(self.tab_6)
        self.RV_reset.setObjectName(_fromUtf8("RV_reset"))
        self.horizontalLayout_15.addWidget(self.RV_reset)
        self.gridLayout_12.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.RV_peptides = QtGui.QTableWidget(self.tab_6)
        self.RV_peptides.setObjectName(_fromUtf8("RV_peptides"))
        self.RV_peptides.setColumnCount(4)
        self.RV_peptides.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.RV_peptides.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.RV_peptides.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.RV_peptides.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.RV_peptides.setHorizontalHeaderItem(3, item)
        self.gridLayout_12.addWidget(self.RV_peptides, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.RV_up = QtGui.QPushButton(self.tab_6)
        self.RV_up.setObjectName(_fromUtf8("RV_up"))
        self.horizontalLayout_13.addWidget(self.RV_up)
        self.RV_down = QtGui.QPushButton(self.tab_6)
        self.RV_down.setObjectName(_fromUtf8("RV_down"))
        self.horizontalLayout_13.addWidget(self.RV_down)
        self.gridLayout_12.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 3, 0, 1, 1)
        self.RV_accepted_peptides = QtGui.QTableWidget(self.tab_6)
        self.RV_accepted_peptides.setObjectName(_fromUtf8("RV_accepted_peptides"))
        self.RV_accepted_peptides.setColumnCount(3)
        self.RV_accepted_peptides.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.RV_accepted_peptides.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.RV_accepted_peptides.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.RV_accepted_peptides.setHorizontalHeaderItem(2, item)
        self.gridLayout_12.addWidget(self.RV_accepted_peptides, 4, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.RV_remove = QtGui.QPushButton(self.tab_6)
        self.RV_remove.setObjectName(_fromUtf8("RV_remove"))
        self.horizontalLayout_14.addWidget(self.RV_remove)
        self.RV_save = QtGui.QPushButton(self.tab_6)
        self.RV_save.setObjectName(_fromUtf8("RV_save"))
        self.horizontalLayout_14.addWidget(self.RV_save)
        self.gridLayout_12.addLayout(self.horizontalLayout_14, 5, 0, 1, 1)
        self.gridLayout_12.setRowStretch(1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_24 = QtGui.QLabel(self.tab_6)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_5.addWidget(self.label_24)
        self.RV_stats = QtGui.QTableWidget(self.tab_6)
        self.RV_stats.setObjectName(_fromUtf8("RV_stats"))
        self.RV_stats.setColumnCount(1)
        self.RV_stats.setRowCount(13)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.RV_stats.setHorizontalHeaderItem(0, item)
        self.verticalLayout_5.addWidget(self.RV_stats)
        self.gridLayout_11.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_6.addWidget(self.label_23)
        self.RV_HM = PlotWidget(self.tab_6)
        self.RV_HM.setObjectName(_fromUtf8("RV_HM"))
        self.verticalLayout_6.addWidget(self.RV_HM)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_15 = QtGui.QLabel(self.tab_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_7.addWidget(self.label_15)
        self.RV_EIC = PlotWidget(self.tab_6)
        self.RV_EIC.setObjectName(_fromUtf8("RV_EIC"))
        self.verticalLayout_7.addWidget(self.RV_EIC)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_22 = QtGui.QLabel(self.tab_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_11.addWidget(self.label_22)
        self.RV_MS_RB = QtGui.QRadioButton(self.tab_6)
        self.RV_MS_RB.setChecked(True)
        self.RV_MS_RB.setObjectName(_fromUtf8("RV_MS_RB"))
        self.horizontalLayout_11.addWidget(self.RV_MS_RB)
        self.RV_MSMS_RB = QtGui.QRadioButton(self.tab_6)
        self.RV_MSMS_RB.setObjectName(_fromUtf8("RV_MSMS_RB"))
        self.horizontalLayout_11.addWidget(self.RV_MSMS_RB)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.RV_spectrum = PlotWidget(self.tab_6)
        self.RV_spectrum.setObjectName(_fromUtf8("RV_spectrum"))
        self.verticalLayout_8.addWidget(self.RV_spectrum)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.RV_accept = QtGui.QPushButton(self.tab_6)
        self.RV_accept.setObjectName(_fromUtf8("RV_accept"))
        self.horizontalLayout_17.addWidget(self.RV_accept)
        self.RV_reject = QtGui.QPushButton(self.tab_6)
        self.RV_reject.setObjectName(_fromUtf8("RV_reject"))
        self.horizontalLayout_17.addWidget(self.RV_reject)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.gridLayout_8.addLayout(self.verticalLayout_8, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_13.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Select Input Data", None))
        self.T_browse_mascot.setText(_translate("Dialog", "Browse", None))
        self.label_2.setText(_translate("Dialog", "Mascot", None))
        self.label_3.setText(_translate("Dialog", "HiTIME", None))
        item = self.T_HT_files.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Filename", None))
        item = self.T_HT_files.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Charge", None))
        self.T_HT_add.setText(_translate("Dialog", "Add", None))
        self.T_HT_remove.setText(_translate("Dialog", "Remove", None))
        self.groupBox_2.setTitle(_translate("Dialog", "CRM Specification", None))
        self.label_4.setText(_translate("Dialog", "All Modifications", None))
        self.label_5.setText(_translate("Dialog", "CRM Modifications", None))
        item = self.T_CRM_mods.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name", None))
        item = self.T_CRM_mods.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Mass", None))
        self.T_mods_add.setText(_translate("Dialog", "Add  --->", None))
        self.T_mods_remove.setText(_translate("Dialog", "<--- Remove", None))
        item = self.T_all_mods.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name", None))
        item = self.T_all_mods.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Mass", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Search Parameters", None))
        self.label_6.setText(_translate("Dialog", "HiTIME score cutoff", None))
        self.T_remove_duplicates.setText(_translate("Dialog", "Remove Duplicates", None))
        self.T_get_indirect.setText(_translate("Dialog", "Get Indirect", None))
        self.label_8.setText(_translate("Dialog", "Minimum RT between HT peaks", None))
        self.T_plot_EICs.setText(_translate("Dialog", "Plot EICs", None))
        self.label_7.setText(_translate("Dialog", "Minimum mz between HT peaks", None))
        self.label.setText(_translate("Dialog", "MS1 mzML", None))
        self.T_browse_mzML.setText(_translate("Dialog", "Browse", None))
        self.label_10.setText(_translate("Dialog", "Neutral isotope mass difference", None))
        self.label_11.setText(_translate("Dialog", "MS2 mzML", None))
        self.T_browse_mzML2.setText(_translate("Dialog", "Browse", None))
        self.label_12.setText(_translate("Dialog", "HT-peptide correlation RT", None))
        self.label_13.setText(_translate("Dialog", "EIC Width +/- mz", None))
        self.label_14.setText(_translate("Dialog", "HT-peptide correlation m/z", None))
        self.label_9.setText(_translate("Dialog", "Output File Name", None))
        self.T_outputFile_button.setText(_translate("Dialog", "Browse", None))
        self.T_run.setText(_translate("Dialog", "Run Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Targeted PTM search", None))
        self.RV_load_results.setText(_translate("Dialog", "Load Results", None))
        self.RV_reset.setText(_translate("Dialog", "Reset", None))
        item = self.RV_peptides.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.RV_peptides.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Type", None))
        item = self.RV_peptides.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "RT", None))
        item = self.RV_peptides.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "m/z", None))
        self.RV_up.setText(_translate("Dialog", "Up", None))
        self.RV_down.setText(_translate("Dialog", "Down", None))
        self.label_25.setText(_translate("Dialog", "Accepted peptides", None))
        item = self.RV_accepted_peptides.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.RV_accepted_peptides.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Peptide", None))
        item = self.RV_accepted_peptides.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Protein", None))
        self.RV_remove.setText(_translate("Dialog", "Remove", None))
        self.RV_save.setText(_translate("Dialog", "Save Results", None))
        self.label_24.setText(_translate("Dialog", "Peptide Results", None))
        item = self.RV_stats.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Sequence", None))
        item = self.RV_stats.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Charge", None))
        item = self.RV_stats.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "Missed Cleavage", None))
        item = self.RV_stats.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "Mod String", None))
        item = self.RV_stats.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "Score", None))
        item = self.RV_stats.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "Identity", None))
        item = self.RV_stats.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "Homology", None))
        item = self.RV_stats.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "Protein", None))
        item = self.RV_stats.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "Protein ACC", None))
        item = self.RV_stats.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "Peptide m/z", None))
        item = self.RV_stats.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "Peptide RT", None))
        item = self.RV_stats.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "HT m/z", None))
        item = self.RV_stats.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "HT RT", None))
        item = self.RV_stats.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Value", None))
        self.label_23.setText(_translate("Dialog", "Heat Map", None))
        self.label_15.setText(_translate("Dialog", "EIC", None))
        self.label_22.setText(_translate("Dialog", "Spectrum", None))
        self.RV_MS_RB.setText(_translate("Dialog", "MS", None))
        self.RV_MSMS_RB.setText(_translate("Dialog", "MS/MS", None))
        self.RV_accept.setText(_translate("Dialog", "Accept", None))
        self.RV_reject.setText(_translate("Dialog", "Reject", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Results Viewer", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

